[package]
name = "swc_class_decorator"
version = "1.2.0"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
serde = { version = "1.0.229" }
swc_core = { version = "80.0.0", features = ["ecma_plugin_transform", "ecma_transforms", "testing_transform"] }
swc_ecma_parser = { version = "45.1.4", features = ["typescript"] }
swc_ecma_utils = { version = "35.0.2" }

# .cargo/config.toml defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
